services:
  api:
    container_name: fastapi-server
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile.dev"
    
    env_file:
      - "../.env.dev"
    
    ports:
      - "8000:8000"
    
    volumes:
      - "../src/mafia_backend:/app/mafia_backend"

  db:
    container_name: database
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile.sql"

    env_file: 
      - "../.env.dev"

    ports:
      - "3306:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_data
  